version: "3.9"

services:
  db:
    container_name: golang-echo-api-db
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  
  api:
    container_name: golang-echo-api-api
    build:
      context: ../.
      dockerfile: docker/Dockerfile.local
    command: air
    volumes:
      - ../.:/app/:rw
    ports:
      - '1323:1323'
    env_file:
      - ../.env

